"""Second Migration

Revision ID: 36d7e1450d57
Revises: e0c644b9a85a
Create Date: 2019-02-16 13:41:45.710044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d7e1450d57'
down_revision = 'e0c644b9a85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author_name')
    # ### end Alembic commands ###
