"""Fifth Migration

Revision ID: 750840334476
Revises: 7f24ef3ea2ea
Create Date: 2019-02-16 19:54:33.501179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750840334476'
down_revision = '7f24ef3ea2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###
